export interface Location {
  emoji: string;
  name: string;
  vocab: string[];
}

export const LOCATIONS: Location[] = [
  // ─── CAAFIMAAD (Medical) ────────────────────────────────────────────
  { emoji: "🏥", name: "Isbitaal", vocab: ["bukaan", "dhakhtarka", "dawo", "qaliin", "kalkaaliye", "sariir", "daaweyn"] },
  { emoji: "🦷", name: "Rugta Ilkaha", vocab: ["il", "qanjidhada", "cirbad", "xanuun", "calaf", "garaaca", "dhakhtarka"] },
  { emoji: "👁️", name: "Rugta Indhaha", vocab: ["indho", "aragga", "muraayadda", "aragti", "iftiinka", "daaweyn", "baaritaan"] },
  { emoji: "🤰", name: "Rugta Dhalmada", vocab: ["hooyada", "ilmaha", "dhalasho", "uur", "kalkaaliye", "daryeelka", "nafta"] },
  { emoji: "🚑", name: "Qaybta Degdegga", vocab: ["degdeg", "nabar", "baabuurta", "xaaladda", "gargaar", "nafta", "dhibaato"] },
  { emoji: "🧠", name: "Isbitaalka Nafsi", vocab: ["maskaxda", "dareemaha", "nafsi", "xaalad", "daaweyn", "xiriir", "jilicsan"] },
  { emoji: "💊", name: "Farmashiyaha", vocab: ["dawo", "kiis", "qiimaha", "warqad", "daaweyn", "nidaam", "macaamiil"] },
  { emoji: "🔬", name: "Sheybaarka Caafimaadka", vocab: ["baaritaan", "dhiig", "cilmi", "natiijooyinka", "sawir", "xoojiye", "hub"] },
  { emoji: "🩺", name: "Rugta Xanuunka Laabta", vocab: ["wadnaha", "jirka", "xididdada", "dhacdada", "daaweyn", "maraakiibta", "awood"] },
  { emoji: "🏃", name: "Xarunta Dib-u-Celinta Caafimaadka", vocab: ["jimicsi", "soo kac", "jirka", "caafimaad", "tababar", "xoog", "horumar"] },
  { emoji: "🧬", name: "Rugta Cilmiga Hidda-wadaha", vocab: ["hidda", "jeermis", "baaritaan", "nidaam", "cilmi", "sayniska", "ogaansha"] },
  { emoji: "🩻", name: "Rugta X-ray", vocab: ["lafaha", "sawir", "qaliin", "baaritaan", "nidaam", "xog", "dawo"] },
  { emoji: "🧪", name: "Lab-ka Caafimaadka", vocab: ["shaybaadhka", "cilmi", "baaritaan", "xog", "nidaam", "natiijooyinka", "hub"] },
  { emoji: "🫁", name: "Rugta Sambabka", vocab: ["sambab", "neefsashada", "jirka", "xanuun", "daaweyn", "baaritaan", "xog"] },
  { emoji: "🐾", name: "Rugta Xoolaha (Vet)", vocab: ["xoolaha", "dhakhtarka", "dawo", "nabar", "daryeel", "baaritaan", "diiwaanka"] },
  { emoji: "👶", name: "Isbitaalka Carruurta", vocab: ["carruura", "hooyada", "dawo", "daryeel", "kalkaaliye", "bukaan", "nafta"] },
  { emoji: "🧓", name: "Xarunta Waayeelka", vocab: ["waayeelka", "daryeel", "nasasho", "caafimaad", "xaaladda", "gargaar", "jirka"] },
  { emoji: "💉", name: "Goobta Tallaalka", vocab: ["tallaal", "cirbad", "dawo", "ilaalinta", "xoogga", "dhiig", "daryeel"] },
  { emoji: "🧘", name: "Rugta Xaaladda Maskaxda", vocab: ["nabad", "maskax", "dareema", "xasillo", "nafsi", "caafimaad", "jilicsan"] },
  { emoji: "🩹", name: "Rugta Nabarada", vocab: ["nabar", "daaweyn", "xidid", "hub", "xanuun", "gargaar", "kalkaaliye"] },
  { emoji: "🫀", name: "Rugta Wadnaha", vocab: ["wadne", "dhiig", "pumping", "xidid", "daaweyn", "baaritaan", "caafimaad"] },
  { emoji: "🦴", name: "Rugta Lafaha", vocab: ["lafaha", "xanuun", "qaliin", "baaritaan", "daaweyn", "jirka", "xoog"] },
  { emoji: "😷", name: "Goobta Karantiilka", vocab: ["karantiil", "jeermis", "ilaalin", "nidaam", "xayiraad", "xog", "dawo"] },
  { emoji: "🔭", name: "Rugta Barnaamijka Caafimaadka", vocab: ["barnaamij", "caafimaad", "shaqaale", "tababar", "aqoon", "nidaam", "wax barasho"] },
  { emoji: "🏋️", name: "Gym", vocab: ["jimicsi", "jirka", "caafimaad", "tababar", "xoog", "nidaam", "koox"] },

  // ─── WAXBARASHO (Education) ─────────────────────────────────────────
  { emoji: "🏫", name: "Iskuulka Hoose", vocab: ["arday", "macallin", "buug", "fasal", "barashada", "ciyaar", "sanad"] },
  { emoji: "🏫", name: "Dugsi Dhexe", vocab: ["arday", "imtixaan", "macallin", "xisaab", "luqad", "barashada", "waxbarasho"] },
  { emoji: "🏫", name: "Dugsi Sare", vocab: ["arday", "shahaado", "imtixaan", "macallin", "mustaqbal", "barashada", "aqoon"] },
  { emoji: "🎓", name: "Jaamacad", vocab: ["ardayda", "professor", "shahaado", "kulliyad", "cilmi", "barashada", "aqoon"] },
  { emoji: "📚", name: "Maktabad", vocab: ["buug", "aqrinta", "aqoon", "fariishada", "xog", "wax barasho", "qoraalo"] },
  { emoji: "🕌", name: "Dugsi Diineed", vocab: ["quraanka", "salaad", "macallin", "waxbarasho", "diinta", "arday", "aqoon"] },
  { emoji: "🎨", name: "Dugsi Farshaxanka", vocab: ["farshaxan", "midabyo", "sawirada", "tacliimta", "abuuris", "fanaan", "nidaam"] },
  { emoji: "💻", name: "Xarunta Teknoolajiyada", vocab: ["kombiyuutar", "barnaamij", "internet", "tignoolajiya", "wax barasho", "code", "nidaam"] },
  { emoji: "🧑‍🏫", name: "Xarunta Tababarka Xirfadaha", vocab: ["xirfad", "tababar", "shaqo", "aqoon", "macallin", "nidaam", "horumar"] },
  { emoji: "🎒", name: "Goobta Ardayda", vocab: ["ardayda", "nasasho", "ciyaar", "xiriir", "cunto", "saaxiib", "maalinta"] },
  { emoji: "🔭", name: "Sheybaarka Sayniska", vocab: ["cilmi", "sahmin", "tijaabooyinka", "baaritaan", "nidaam", "aqoon", "shaybaadhka"] },
  { emoji: "🖥️", name: "Qolka Kombiyuutarka", vocab: ["kombiyuutar", "internet", "code", "wax barasho", "barnaamij", "nidaam", "xog"] },
  { emoji: "🏟️", name: "Garoonka Iskuulka", vocab: ["ciyaar", "koox", "tartanka", "garoon", "barbaarinta", "arday", "xilliga"] },
  { emoji: "🎵", name: "Xarunta Muusigga", vocab: ["muusig", "hees", "codad", "fanaan", "tababar", "aaladaha", "barashada"] },
  { emoji: "🗣️", name: "Xarunta Luqadaha", vocab: ["luqad", "wax barasho", "hadal", "aqoon", "macallin", "barashada", "nidaam"] },
  { emoji: "🧮", name: "Xarunta Xisaabta", vocab: ["xisaab", "tiro", "falanqayn", "cilmi", "wax barasho", "aqoon", "nidaam"] },
  { emoji: "📐", name: "Xarunta Injineerinnimada", vocab: ["injineer", "dhisme", "nidaam", "cilmi", "tignoolajiya", "aqoon", "mashiinka"] },
  { emoji: "🌍", name: "Xarunta Bulshada", vocab: ["bulshada", "barashada", "aqoon", "xiriir", "nidaam", "dhaqan", "cilmi"] },
  { emoji: "🎭", name: "Xarunta Fanka Riwaayad", vocab: ["riwaayad", "fanaan", "rehearsal", "barashada", "muuqaal", "nidaam", "tababar"] },
  { emoji: "📜", name: "Xarunta Taariikhda", vocab: ["taariikh", "aqoon", "diiwaanka", "xog", "cilmi", "wax barasho", "nidaam"] },

  // ─── DIINTA (Religion) ──────────────────────────────────────────────
  { emoji: "🕌", name: "Masaajid", vocab: ["salaad", "quraanka", "wadaad", "wuduu", "jama'ac", "ducada", "diinta"] },
  { emoji: "⛪", name: "Kaniisad", vocab: ["cibaadd", "wadaad", "diinta", "qoyska", "duqsi", "kitaabka", "ducada"] },
  { emoji: "🛕", name: "Macbad", vocab: ["caabud", "diinta", "xafladda", "nabad", "baryo", "tukasho", "dhaqan"] },
  { emoji: "🕍", name: "Sunagoog", vocab: ["cibaadd", "diinta", "kitaabka", "jama'ac", "baryo", "dhaqan", "ducada"] },
  { emoji: "🌙", name: "Goobta Ciida", vocab: ["ciid", "salaad", "farxad", "jama'ac", "xafladda", "qoyska", "diinta"] },
  { emoji: "📿", name: "Xarunta Dhaqanka Diinta", vocab: ["dhaqan", "diinta", "barashada", "aqoon", "nidaam", "wadaad", "cilmi"] },
  { emoji: "🧎", name: "Goobta Salaadda", vocab: ["salaad", "tukasho", "cibaadd", "wuduu", "jiho", "diinta", "nabad"] },
  { emoji: "📖", name: "Xarunta Axfoojinta Quraanka", vocab: ["quraanka", "xafid", "wax barasho", "macallin", "arday", "aqoon", "diinta"] },
  { emoji: "🌿", name: "Goobta Baryo-galista", vocab: ["baryo", "ducada", "nabad", "xasillo", "diinta", "cibaadd", "qalbi"] },
  { emoji: "🎇", name: "Goobta Xafladda Diinta", vocab: ["xaflad", "ciid", "farxad", "jama'ac", "cunto", "diinta", "dhaqan"] },
  { emoji: "📗", name: "Xarunta Cilmiga Diinta", vocab: ["cilmi", "diinta", "macallin", "aqoon", "kitaabka", "barashada", "nidaam"] },
  { emoji: "🕊️", name: "Goobta Nabad-gelinta", vocab: ["nabad", "xasillo", "diinta", "qalbi", "baryo", "ducada", "jilicsan"] },
  { emoji: "💫", name: "Xarunta Suufiyada", vocab: ["suufi", "dhaqan", "diinta", "nabad", "baryo", "aqoon", "xasillo"] },
  { emoji: "🌺", name: "Goobta Xafladda Barashada Diinta", vocab: ["xaflad", "diinta", "barashada", "farxad", "shahaado", "jama'ac", "aqoon"] },
  { emoji: "🕯️", name: "Xarunta Xusuusta", vocab: ["xusuus", "xugusto", "diinta", "ducada", "qalbi", "nabad", "baryo"] },
  { emoji: "🏕️", name: "Mushaarka Diiniga", vocab: ["farxad", "ciyaar", "wax barasho", "diinta", "jama'ac", "ardayda", "nidaam"] },
  { emoji: "🎋", name: "Goobta Dhaqanka", vocab: ["dhaqan", "diinta", "nabad", "baryo", "cibaadd", "xasillo", "jama'ac"] },
  { emoji: "🏮", name: "Goobta Dugsiga Xaaladda", vocab: ["xaaladda", "diinta", "barashada", "gargaar", "aqoon", "nidaam", "ducada"] },
  { emoji: "🌙", name: "Goobta Ramadaanka", vocab: ["ramadan", "soom", "diinta", "jama'ac", "cunto", "xasillo", "ducada"] },
  { emoji: "🌟", name: "Xarunta Barakaysan", vocab: ["barako", "diinta", "ducada", "nabad", "baryo", "xasillo", "qalbi"] },

  // ─── GANACSIGA (Commerce/Shopping) ──────────────────────────────────
  { emoji: "🛒", name: "Suuq", vocab: ["iibsasho", "alaabtaas", "qiime", "ganacsade", "lacag", "macaamiil", "dhar"] },
  { emoji: "🏪", name: "Dukaan Yar", vocab: ["dukaan", "iib", "alaabtaas", "lacag", "macaamiil", "saaxiib", "qiime"] },
  { emoji: "🏬", name: "Xarunta Xawaashaanta", vocab: ["malls", "dhar", "cunto", "lacag", "iibsasho", "macaamiil", "nidaam"] },
  { emoji: "🛍️", name: "Suuqa Dharka", vocab: ["dhar", "iibsasho", "fashadaha", "qiime", "macaamiil", "nidaam", "lacag"] },
  { emoji: "🥦", name: "Suuqa Khudaarta", vocab: ["khudaar", "cunto", "dhadhan", "iibsasho", "qiime", "macaamiil", "freshness"] },
  { emoji: "🍖", name: "Suuqa Hilibka", vocab: ["hilib", "ganacsade", "qiime", "iib", "macaamiil", "cunto", "dhadhan"] },
  { emoji: "📱", name: "Dukaanka Telefonnada", vocab: ["telefon", "tignoolajiya", "xidid", "nidaam", "internet", "alaabtaas", "qiime"] },
  { emoji: "👗", name: "Dukaanka Dhar-Dumarka", vocab: ["dhar", "fashadaha", "dumarka", "qiime", "iibsasho", "macaamiil", "casri"] },
  { emoji: "👟", name: "Dukaanka Kabbaha", vocab: ["kabbo", "dhar", "qiime", "iibsasho", "nidaam", "fashadaha", "macaamiil"] },
  { emoji: "💍", name: "Dukaanka Dahab-iyo-Lacagta", vocab: ["dahab", "lacag", "qiime", "iibsasho", "qurux", "macaamiil", "nidaam"] },
  { emoji: "📚", name: "Dukaanka Buugaagta", vocab: ["buug", "qoraallada", "aqoon", "aqrinta", "qiime", "macaamiil", "nidaam"] },
  { emoji: "🌺", name: "Suuqa Ubaxa", vocab: ["ubax", "qurux", "qiime", "iibsasho", "midabyo", "macaamiil", "nidaam"] },
  { emoji: "🪑", name: "Dukaanka Alaabta Guriga", vocab: ["alaab", "guriga", "qiime", "iibsasho", "macaamiil", "nidaam", "casri"] },
  { emoji: "🔧", name: "Dukaanka Qalab-gacmeedka", vocab: ["qalab", "nidaam", "shaqo", "gacanta", "qiime", "iib", "macaamiil"] },
  { emoji: "💊", name: "Dukaanka Dawooyinka", vocab: ["dawo", "caafimaad", "nidaam", "qiime", "macaamiil", "kalkaaliye", "hub"] },
  { emoji: "🎁", name: "Dukaanka Hadiyaha", vocab: ["hadiye", "farxad", "qiime", "iibsasho", "macaamiil", "nidaam", "xaflad"] },
  { emoji: "🧴", name: "Suuqa Xawaashaanta Quruxda", vocab: ["qurux", "xawaash", "midabyo", "macaamiil", "qiime", "nidaam", "duf"] },
  { emoji: "🛻", name: "Suuqa Baabuurta", vocab: ["baabuur", "iibsasho", "qiime", "macaamiil", "nidaam", "shaqo", "ganacsi"] },
  { emoji: "🎮", name: "Dukaanka Ciyaaraha", vocab: ["ciyaar", "nidaam", "tignoolajiya", "farxad", "macaamiil", "qiime", "casri"] },
  { emoji: "🪴", name: "Dukaanka Beerta", vocab: ["beerta", "ubax", "geed", "qiime", "iibsasho", "macaamiil", "nidaam"] },
  { emoji: "🛒", name: "Isupermarketka", vocab: ["isupermarket", "cunto", "alaab", "qiime", "iibsasho", "lacag", "macaamiil"] },
  { emoji: "🏗️", name: "Goobta Dhismaha (Guri)", vocab: ["dhisme", "qalabka", "shaqaale", "nidaam", "lacag", "ganacsi", "guriga"] },
  { emoji: "🎪", name: "Goobta Bandhigga (Exhibition)", vocab: ["bandhig", "alaabtaas", "iibsasho", "macaamiil", "nidaam", "horumar", "xaflad"] },
  { emoji: "🛥️", name: "Goobta Kalluunka", vocab: ["kalluun", "badda", "iibsasho", "qiime", "ganacsade", "macaamiil", "cunto"] },
  { emoji: "🧃", name: "Goobta Mashruubka", vocab: ["cabitaan", "biyo", "dhadhan", "qiime", "macaamiil", "nidaam", "cuno"] },
  { emoji: "🎸", name: "Dukaanka Aaladaha Muusigga", vocab: ["muusig", "aaladaha", "codad", "qiime", "iibsasho", "macaamiil", "fanaan"] },
  { emoji: "🐟", name: "Suuqa Kalluunka", vocab: ["kalluun", "baad", "qiime", "iibsasho", "macaamiil", "badda", "cunto"] },
  { emoji: "🧹", name: "Dukaanka Alaabta Nadaafada", vocab: ["nadaafad", "alaab", "qiime", "macaamiil", "nidaam", "iibsasho", "guriga"] },
  { emoji: "⌚", name: "Dukaanka Saacadaha", vocab: ["saacad", "waqti", "qiime", "iibsasho", "macaamiil", "nidaam", "dahab"] },
  { emoji: "🎩", name: "Dukaanka Kuliyadaha", vocab: ["kuliyadda", "dhar", "qiime", "iibsasho", "macaamiil", "nidaam", "fashadaha"] },

  // ─── CUNTADA (Food & Dining) ─────────────────────────────────────────
  { emoji: "🍽️", name: "Makhaayad", vocab: ["cunto", "dhadhan", "jiko", "macaamiil", "shaqaale", "cabitaan", "hilib"] },
  { emoji: "☕", name: "Coffee Shop", vocab: ["qaxwe", "shaah", "cabitaan", "macaamiil", "nasasho", "muusig", "xilliga"] },
  { emoji: "🍕", name: "Guri Cuntada Daaqdaaqaha", vocab: ["pizza", "cunto", "dhadhan", "macaamiil", "qiime", "jiko", "nidaam"] },
  { emoji: "🍔", name: "Makhaayada Xawliidka", vocab: ["burger", "xawliid", "cunto", "dhadhan", "macaamiil", "qiime", "jiko"] },
  { emoji: "🌮", name: "Makhaayada Cuntada Afrikada", vocab: ["cunto", "Afrika", "dhadhan", "hilib", "macaamiil", "qiime", "jiko"] },
  { emoji: "🍜", name: "Makhaayada Cuntada Aasiya", vocab: ["cunto", "Aasiya", "baaris", "dhadhan", "macaamiil", "qiime", "nidaam"] },
  { emoji: "🥗", name: "Makhaayada Cuntada Caafimaadka", vocab: ["khudaar", "caafimaad", "dhadhan", "macaamiil", "xoog", "nidaam", "cunto"] },
  { emoji: "🍰", name: "Bakeri", vocab: ["rooti", "keeg", "macaan", "dhadhan", "macaamiil", "qiime", "jiko"] },
  { emoji: "🍦", name: "Goobta Aaiska Creamka", vocab: ["aaiska", "macaan", "dhadhan", "carruurta", "macaamiil", "qiime", "cabitaan"] },
  { emoji: "🥩", name: "Makhaayada Hilibka", vocab: ["hilib", "dhadhan", "dab", "macaamiil", "qiime", "jiko", "cunto"] },
  { emoji: "🐟", name: "Makhaayada Kalluunka", vocab: ["kalluun", "badda", "dhadhan", "macaamiil", "qiime", "jiko", "cunto"] },
  { emoji: "🫕", name: "Makhaayada Maraqda", vocab: ["maraq", "dhadhan", "macaamiil", "qiime", "jiko", "hilib", "cunto"] },
  { emoji: "🍱", name: "Makhaayada Cuntada Xabaalaha", vocab: ["cunto", "packaging", "macaamiil", "dhadhan", "qiime", "nidaam", "jiko"] },
  { emoji: "🥘", name: "Makhaayada Baraiska", vocab: ["baaris", "dhadhan", "macaamiil", "qiime", "hilib", "jiko", "cunto"] },
  { emoji: "🥞", name: "Makhaayada Subaxnimada", vocab: ["subax", "cunto", "cabitaan", "dhadhan", "macaamiil", "qiime", "rooti"] },
  { emoji: "🧃", name: "Goobta Cabitaanka Miraha", vocab: ["miraha", "cabitaan", "dhadhan", "macaamiil", "qiime", "nidaam", "biyo"] },
  { emoji: "🍗", name: "Makhaayada Digaagga", vocab: ["digaag", "dhadhan", "macaamiil", "qiime", "jiko", "cunto", "hilib"] },
  { emoji: "🥙", name: "Makhaayada Sangawiishka", vocab: ["sangawiish", "cunto", "dhadhan", "macaamiil", "qiime", "jiko", "nidaam"] },
  { emoji: "🫖", name: "Goobta Shaaha", vocab: ["shaah", "cabitaan", "dhadhan", "macaamiil", "qiime", "nidaam", "biyo"] },
  { emoji: "🍩", name: "Bakeri (Donat)", vocab: ["donat", "macaan", "dhadhan", "macaamiil", "qiime", "keeg", "jiko"] },
  { emoji: "🎂", name: "Goobta Keegga", vocab: ["keeg", "xaflad", "macaan", "dhadhan", "macaamiil", "farxad", "nidaam"] },
  { emoji: "🍖", name: "Makhaayada Barbecue", vocab: ["BBQ", "dab", "hilib", "dhadhan", "macaamiil", "qiime", "jiko"] },
  { emoji: "🫙", name: "Goobta Barafka (Cabitaan)", vocab: ["baraf", "cabitaan", "macaan", "dhadhan", "macaamiil", "qiime", "xilliga"] },
  { emoji: "🍶", name: "Goobta Cabitaanka Afrikada", vocab: ["cabitaan", "dhaqan", "dhadhan", "macaamiil", "qiime", "Afrika", "nidaam"] },
  { emoji: "🥣", name: "Makhaayada Xatooda (Porridge)", vocab: ["xatooda", "subax", "cunto", "dhadhan", "macaamiil", "qiime", "nafaqo"] },

  // ─── GAADIIDKA (Transportation) ──────────────────────────────────────
  { emoji: "✈️", name: "Garoon Diyaaradeed", vocab: ["diyaarad", "safar", "tiket", "rakaab", "baasaboor", "duul", "dalka"] },
  { emoji: "🚂", name: "Saldhigga Tareenka", vocab: ["tareen", "safar", "tiket", "rakaab", "saldhig", "nidaam", "dalka"] },
  { emoji: "🚢", name: "Deked", vocab: ["markab", "badda", "safar", "xamuul", "rakaab", "deked", "nidaam"] },
  { emoji: "🚌", name: "Saldhigga Baska", vocab: ["baska", "safar", "tiket", "rakaab", "nidaam", "saldhig", "jidka"] },
  { emoji: "🚕", name: "Goobta Taaksiga", vocab: ["taaksi", "safar", "lacag", "jidka", "baabuur", "nidaam", "macaamiil"] },
  { emoji: "🛳️", name: "Markabka Dadweynaha", vocab: ["markab", "badda", "rakaab", "safar", "tiket", "nidaam", "deked"] },
  { emoji: "🚁", name: "Goobta Hallaybaariga", vocab: ["hallaybaarig", "duul", "safar", "degdeg", "nidaam", "xog", "hawada"] },
  { emoji: "⛽", name: "Goobta Shidaalka", vocab: ["shidaal", "baabuur", "nidaam", "qiime", "lacag", "macaamiil", "xidid"] },
  { emoji: "🔧", name: "Goobta Dayactirka Baabuurta", vocab: ["dayactir", "baabuur", "xidid", "nidaam", "qalab", "shaqaale", "ganacsi"] },
  { emoji: "🚦", name: "Bartamaha Raadka", vocab: ["jidka", "nidaam", "baabuur", "safar", "daaweyn", "gaadiid", "booliska"] },
  { emoji: "🅿️", name: "Goobta Baabuurta", vocab: ["baabuur", "parking", "jidka", "nidaam", "lacag", "macaamiil", "goob"] },
  { emoji: "🚲", name: "Goobta Baaskiilka", vocab: ["baaskiil", "safar", "caafimaad", "nidaam", "jidka", "jimicsi", "ciyaar"] },
  { emoji: "🛵", name: "Goobta Motorbaiskiilka", vocab: ["motor", "safar", "jidka", "lacag", "nidaam", "gaadiid", "xawli"] },
  { emoji: "🚉", name: "Xarunta Gaadiidka Guud", vocab: ["gaadiid", "safar", "nidaam", "rakaab", "tiket", "jidka", "saldhig"] },
  { emoji: "🛤️", name: "Jidka Tareenka", vocab: ["tareen", "jidka", "nidaam", "safar", "dalka", "baabuur", "gaadiid"] },
  { emoji: "🌁", name: "Buundada (Bridge)", vocab: ["buundo", "jidka", "nidaam", "safar", "baabuur", "dhisme", "dalka"] },
  { emoji: "🚧", name: "Goobta Dhismaha Jidka", vocab: ["dhisme", "jidka", "shaqaale", "nidaam", "qalab", "baabuur", "xidid"] },
  { emoji: "⚓", name: "Dekedda Kalluunka", vocab: ["kalluun", "badda", "doon", "nidaam", "safar", "deked", "ganacsade"] },
  { emoji: "🗺️", name: "Goobta Wadada", vocab: ["jidka", "safar", "nidaam", "xog", "diiwaanka", "baabuur", "gaadiid"] },
  { emoji: "🛺", name: "Goobta Bajaajiilka (Tuk-tuk)", vocab: ["bajaajiil", "safar", "lacag", "jidka", "nidaam", "macaamiil", "gaadiid"] },
  { emoji: "🚡", name: "Goobta Raadka Hawada", vocab: ["raad", "hawada", "safar", "nidaam", "jidka", "macaamiil", "gaadiid"] },
  { emoji: "🛣️", name: "Wadada Weyn (Highway)", vocab: ["wadada", "jidka", "baabuur", "safar", "nidaam", "gaadiid", "dheerna"] },
  { emoji: "🚏", name: "Joogsiga Baabuurta", vocab: ["joogsiga", "baska", "rakaab", "nidaam", "tiket", "jidka", "safar"] },
  { emoji: "🏗️", name: "Goobta Dhismaha Buundada", vocab: ["dhisme", "buundo", "nidaam", "shaqaale", "qalab", "jidka", "lacag"] },
  { emoji: "🌊", name: "Xarunta Doonnida", vocab: ["doon", "badda", "safar", "nidaam", "deked", "ganacsade", "mowj"] },

  // ─── MADADAALO (Entertainment) ───────────────────────────────────────
  { emoji: "🎬", name: "Shineemo", vocab: ["film", "daawasho", "muraayadda", "mugdi", "cod", "muusig", "macaamiil"] },
  { emoji: "🎡", name: "Beerta Madadaalada", vocab: ["ciyaar", "carruurta", "farxad", "qayla", "nasasho", "lacag", "nidaam"] },
  { emoji: "🎢", name: "Goobta Roller Coaster", vocab: ["roller", "ciyaar", "farxad", "xawli", "qayla", "carruurta", "nidaam"] },
  { emoji: "🎭", name: "Masraxa", vocab: ["riwaayad", "fanaan", "daawasho", "muusig", "macaamiil", "nidaam", "bandhig"] },
  { emoji: "🎵", name: "Concert Hall", vocab: ["muusig", "heeso", "fanaan", "daawasho", "macaamiil", "nidaam", "codad"] },
  { emoji: "🎯", name: "Goobta Ciyaaraha Xirfada", vocab: ["ciyaar", "xirfad", "tartanka", "macaamiil", "nidaam", "farxad", "lacag"] },
  { emoji: "🎲", name: "Goobta Ciyaaraha Miiska", vocab: ["ciyaar", "miis", "tartan", "nidaam", "farxad", "saaxiib", "lacag"] },
  { emoji: "🎳", name: "Bowling Alley", vocab: ["bowling", "ciyaar", "tartanka", "farxad", "macaamiil", "nidaam", "lacag"] },
  { emoji: "🏊", name: "Berked Dabaasha", vocab: ["dabaashan", "biyo", "ciyaar", "caafimaad", "macaamiil", "nidaam", "xilliga"] },
  { emoji: "🎮", name: "Qolka Ciyaaraha Kombiyuutarka", vocab: ["ciyaar", "video", "kombiyuutar", "farxad", "macaamiil", "nidaam", "lacag"] },
  { emoji: "🃏", name: "Goobta Ciyaaraha Kaarka", vocab: ["kaar", "ciyaar", "tartan", "nidaam", "farxad", "saaxiib", "lacag"] },
  { emoji: "🎪", name: "Goobta Bandhigga", vocab: ["bandhig", "fanaan", "muuqaal", "macaamiil", "nidaam", "farxad", "xaflad"] },
  { emoji: "🏄", name: "Goobta Surfingga", vocab: ["surfing", "badda", "mowj", "ciyaar", "caafimaad", "xawli", "nidaam"] },
  { emoji: "🧗", name: "Goobta Rock Climbing", vocab: ["sare", "buurta", "xoog", "ciyaar", "caafimaad", "tababar", "nidaam"] },
  { emoji: "🎠", name: "Goobta Carousel", vocab: ["ciyaar", "carruurta", "wareegid", "farxad", "macaamiil", "nidaam", "lacag"] },
  { emoji: "🎻", name: "Goobta Kareenka Muusigga", vocab: ["muusig", "fanaan", "kareen", "codad", "macaamiil", "nidaam", "bandhig"] },
  { emoji: "🎤", name: "Goobta Karaoke", vocab: ["karaoke", "heeso", "fanaan", "farxad", "saaxiib", "macaamiil", "nidaam"] },
  { emoji: "🎷", name: "Goobta Jazz", vocab: ["jazz", "muusig", "fanaan", "codad", "macaamiil", "nidaam", "farxad"] },
  { emoji: "🎉", name: "Goobta Xafladaha", vocab: ["xaflad", "farxad", "muusig", "cunto", "saaxiib", "nidaam", "dacwad"] },
  { emoji: "🔮", name: "Goobta Sixirka (Magic Show)", vocab: ["sixir", "muuqaal", "fanaan", "farxad", "macaamiil", "nidaam", "bandhig"] },
  { emoji: "🎡", name: "Carnival", vocab: ["carnival", "ciyaar", "farxad", "macaamiil", "nidaam", "qayla", "lacag"] },
  { emoji: "🃏", name: "Goobta Escape Room", vocab: ["escape", "ciyaar", "tartan", "nidaam", "aqoon", "saaxiib", "farxad"] },
  { emoji: "🌙", name: "Goobta Daawashada Xiddigaha", vocab: ["xiddig", "samada", "muuqaal", "macaamiil", "nidaam", "cilmi", "qabow"] },
  { emoji: "🎟️", name: "Goobta Tiketka", vocab: ["tiket", "nidaam", "macaamiil", "lacag", "safar", "xaflad", "bandhig"] },
  { emoji: "🌅", name: "Goobta Daawashada Qoraxda", vocab: ["qorax", "muuqaal", "macaamiil", "nidaam", "farxad", "nasasho", "xilliga"] },
  { emoji: "🎆", name: "Goobta Iftiinka (Fireworks)", vocab: ["fireworks", "farxad", "xaflad", "muuqaal", "macaamiil", "nidaam", "samada"] },
  { emoji: "🎸", name: "Goobta Rock Concert", vocab: ["rock", "muusig", "fanaan", "codad", "macaamiil", "nidaam", "farxad"] },
  { emoji: "🎺", name: "Goobta Bandhigga Muusigga Dhaqanka", vocab: ["dhaqan", "muusig", "fanaan", "codad", "macaamiil", "nidaam", "taariikh"] },
  { emoji: "🛝", name: "Goobta Ciyaarka Carruurta (Playground)", vocab: ["ciyaar", "carruurta", "farxad", "nasasho", "nidaam", "xilliga", "macaamiil"] },
  { emoji: "🏖️", name: "Xeeb", vocab: ["biyo", "ciid", "mowj", "qorax", "nasasho", "kalluun", "xilliga"] },

  // ─── ISBOORTIGA (Sports) ─────────────────────────────────────────────
  { emoji: "⚽", name: "Garoon Kubadeed", vocab: ["kubad", "ciyaar", "koox", "xiddig", "golka", "tartanka", "garoon"] },
  { emoji: "🏀", name: "Garoon Basketboolka", vocab: ["basketball", "ciyaar", "koox", "tartan", "golka", "garoon", "nidaam"] },
  { emoji: "🏋️", name: "Goobta Dhiiqashada (Weightlifting)", vocab: ["qalab", "xoog", "jimicsi", "tababar", "caafimaad", "nidaam", "awood"] },
  { emoji: "🏊", name: "Goobta Dabaashada", vocab: ["biyo", "ciyaar", "caafimaad", "jimicsi", "tartan", "nidaam", "xog"] },
  { emoji: "🥊", name: "Goobta Boxing", vocab: ["boxing", "xoog", "tababar", "tartan", "ciyaar", "awood", "nidaam"] },
  { emoji: "🏈", name: "Garoon American Football", vocab: ["american football", "ciyaar", "koox", "tartan", "golka", "garoon", "nidaam"] },
  { emoji: "⛳", name: "Goobta Golf", vocab: ["golf", "ciyaar", "garoon", "nidaam", "tartan", "macaamiil", "lacag"] },
  { emoji: "🎾", name: "Goobta Tennis", vocab: ["tennis", "ciyaar", "koox", "tartan", "nidaam", "garoon", "xiddig"] },
  { emoji: "🏐", name: "Garoon Volleyball", vocab: ["volleyball", "ciyaar", "koox", "tartan", "garoon", "nidaam", "golka"] },
  { emoji: "🥋", name: "Goobta Martial Arts", vocab: ["martial arts", "xoog", "tababar", "nidaam", "caafimaad", "tartan", "awood"] },
  { emoji: "🏇", name: "Goobta Ordida Farasku", vocab: ["faras", "tartan", "nidaam", "garoon", "ciyaar", "macaamiil", "xilliga"] },
  { emoji: "🧘", name: "Goobta Yoga", vocab: ["yoga", "nasasho", "caafimaad", "nidaam", "jirka", "jimicsi", "xasillo"] },
  { emoji: "🎿", name: "Goobta Skiing", vocab: ["baraf", "skiing", "ciyaar", "tartan", "nidaam", "xilliga", "xoog"] },
  { emoji: "🏒", name: "Goobta Hockey", vocab: ["hockey", "ciyaar", "koox", "tartan", "garoon", "nidaam", "golka"] },
  { emoji: "🏉", name: "Garoon Rugby", vocab: ["rugby", "ciyaar", "koox", "xoog", "tartan", "garoon", "nidaam"] },
  { emoji: "🎽", name: "Goobta Orodka", vocab: ["orod", "ciyaar", "tartan", "nidaam", "caafimaad", "garoon", "xog"] },
  { emoji: "🤸", name: "Goobta Gymnastics", vocab: ["gymnastics", "jirka", "tababar", "nidaam", "tartan", "caafimaad", "xog"] },
  { emoji: "🏹", name: "Goobta Archery", vocab: ["archery", "tiir", "nidaam", "tartan", "xirfad", "garoon", "macaamiil"] },
  { emoji: "🥌", name: "Goobta Curling", vocab: ["curling", "baraf", "ciyaar", "tartan", "nidaam", "garoon", "xog"] },
  { emoji: "🪂", name: "Goobta Parachute", vocab: ["hawada", "parachute", "ciyaar", "xawli", "nidaam", "tartan", "xog"] },
  { emoji: "🤿", name: "Goobta Diving", vocab: ["badda", "biyo", "diving", "ciyaar", "caafimaad", "nidaam", "tartan"] },
  { emoji: "🧗", name: "Goobta Mountain Climbing", vocab: ["buur", "xoog", "tababar", "nidaam", "ciyaar", "tartan", "awood"] },
  { emoji: "🏌️", name: "Goobta Golf (Club)", vocab: ["golf", "ciyaar", "garoon", "macaamiil", "nidaam", "lacag", "tartan"] },
  { emoji: "🛹", name: "Goobta Skateboarding", vocab: ["skateboard", "ciyaar", "xawli", "xog", "nidaam", "tartan", "carruurta"] },
  { emoji: "⛷️", name: "Goobta Ski Resort", vocab: ["baraf", "skiing", "nasasho", "nidaam", "xilliga", "ciyaar", "macaamiil"] },

  // ─── SHAQADA (Work/Office) ───────────────────────────────────────────
  { emoji: "🏢", name: "Xafiis", vocab: ["shaqo", "shaqaale", "maamul", "xiriir", "nidaam", "kulanka", "wax soo saarta"] },
  { emoji: "🏗️", name: "Goobta Dhismaha", vocab: ["dhisme", "shaqaale", "qalab", "nidaam", "lacag", "ganacsi", "guriga"] },
  { emoji: "🏭", name: "Warshad", vocab: ["warshad", "shaqaale", "wax soo saar", "qalab", "nidaam", "lacag", "alaabtaas"] },
  { emoji: "⚓", name: "Xarunta Badmareenka", vocab: ["badmareen", "badda", "shaqo", "nidaam", "safar", "ganacsade", "deked"] },
  { emoji: "🧑‍🌾", name: "Beer", vocab: ["beer", "beerista", "dhul", "biyo", "khudaar", "nidaam", "xilliga"] },
  { emoji: "🚜", name: "Goobta Beeraha Waaweyn", vocab: ["traktarka", "beer", "dhul", "nidaam", "alaabtaas", "lacag", "ganacsade"] },
  { emoji: "🪵", name: "Warshada Qoriga", vocab: ["qori", "warshad", "shaqaale", "qalab", "nidaam", "lacag", "wax soo saar"] },
  { emoji: "🔩", name: "Warshada Bir-gashka", vocab: ["bir", "warshad", "shaqaale", "qalab", "nidaam", "wax soo saar", "lacag"] },
  { emoji: "🧱", name: "Warshada Dhagxanta", vocab: ["dhagax", "warshad", "shaqaale", "nidaam", "dhisme", "lacag", "qalab"] },
  { emoji: "🔬", name: "Shaybaadhka Cilmiga", vocab: ["cilmi", "baaritaan", "shaybaadhka", "nidaam", "aqoon", "natiijooyinka", "hub"] },
  { emoji: "📡", name: "Xarunta Xiriirka", vocab: ["xiriir", "internet", "nidaam", "tignoolajiya", "shaqo", "lacag", "alaabtaas"] },
  { emoji: "🖨️", name: "Xarunta Daabacaadda", vocab: ["daabacaad", "warqad", "shaqo", "nidaam", "lacag", "alaabtaas", "macaamiil"] },
  { emoji: "🏛️", name: "Xarunta Dowladda", vocab: ["dowlad", "shaqo", "maamul", "nidaam", "sharciga", "xog", "lacag"] },
  { emoji: "💼", name: "Xarunta Shirkadda", vocab: ["shirkad", "shaqo", "maamul", "nidaam", "lacag", "ganacsi", "kulanka"] },
  { emoji: "📊", name: "Xarunta Xisaabaadka", vocab: ["xisaab", "lacag", "nidaam", "xog", "shaqo", "maamul", "shirkad"] },
  { emoji: "🧑‍💻", name: "Goobta IT", vocab: ["code", "kombiyuutar", "nidaam", "internet", "shaqo", "tignoolajiya", "lacag"] },
  { emoji: "🚒", name: "Xarunta Dab-damiska", vocab: ["dab", "gargaar", "shaqaale", "koox", "nidaam", "degdeg", "baabuur"] },
  { emoji: "🚓", name: "Saldhig Booliis", vocab: ["booliska", "sharciga", "nidaam", "shaqaale", "dacwad", "xog", "maamul"] },
  { emoji: "⚖️", name: "Maxkamad", vocab: ["maxkamad", "sharciga", "dacwad", "xukun", "wakiil", "nidaam", "xog"] },
  { emoji: "🏛️", name: "Goobta Sharciga", vocab: ["sharciga", "dacwad", "xukun", "maamul", "nidaam", "xog", "wakiil"] },
  { emoji: "📮", name: "Boosta", vocab: ["warqad", "boosta", "nidaam", "xog", "shaqo", "macaamiil", "lacag"] },
  { emoji: "🏦", name: "Bangi", vocab: ["lacag", "kaydi", "deeq", "shirkad", "macaamiil", "nidaam", "xog"] },
  { emoji: "💰", name: "Xarunta Lacag-bedelka", vocab: ["lacag", "bedel", "nidaam", "macaamiil", "ganacsi", "xog", "shirkad"] },
  { emoji: "🧑‍🔧", name: "Goobta Dayactirka", vocab: ["dayactir", "qalab", "shaqaale", "nidaam", "xidid", "macaamiil", "xog"] },
  { emoji: "🚁", name: "Xarunta Hallaybaariga", vocab: ["hallaybaarig", "safar", "nidaam", "degdeg", "gargaar", "hawada", "shaqo"] },

  // ─── KHIDMADAHA DOWLADDA (Government Services) ───────────────────────
  { emoji: "🏛️", name: "Maamulka Deegaanka", vocab: ["maamul", "dowlad", "sharciga", "nidaam", "shaqo", "dacwad", "xog"] },
  { emoji: "🪪", name: "Xarunta Aqoonsiga", vocab: ["aqoonsi", "nidaam", "sharciga", "xog", "macaamiil", "maamul", "warqad"] },
  { emoji: "📋", name: "Xarunta Diwaangelinta", vocab: ["diiwaanka", "nidaam", "sharciga", "xog", "macaamiil", "maamul", "warqad"] },
  { emoji: "🗳️", name: "Goobta Cod-bixinta", vocab: ["doorasho", "cod", "dowlad", "nidaam", "sharciga", "xog", "muwaadanka"] },
  { emoji: "🧑‍⚖️", name: "Goobta Wakiilka Sharciga", vocab: ["wakiil", "sharciga", "dacwad", "nidaam", "xog", "macaamiil", "maamul"] },
  { emoji: "📜", name: "Xarunta Diiwaanka Qaranka", vocab: ["diiwaanka", "taariikh", "qaranka", "nidaam", "sharciga", "xog", "maamul"] },
  { emoji: "🚔", name: "Qaybta Socdaalka (Immigration)", vocab: ["socdaal", "baasaboor", "nidaam", "sharciga", "xog", "dalka", "maamul"] },
  { emoji: "🏗️", name: "Xarunta Qorshaynta Magaalada", vocab: ["qorsho", "magaalo", "dhisme", "nidaam", "maamul", "lacag", "qabyo"] },
  { emoji: "💡", name: "Xarunta Koronto", vocab: ["koronto", "nidaam", "shaqo", "lacag", "macaamiil", "alaabtaas", "xog"] },
  { emoji: "🚰", name: "Xarunta Biyaha", vocab: ["biyo", "nidaam", "shaqo", "lacag", "macaamiil", "xubnaha", "alaabtaas"] },
  { emoji: "🗑️", name: "Xarunta Qashinka", vocab: ["qashin", "nadiifin", "nidaam", "shaqo", "magaalo", "maamul", "xog"] },
  { emoji: "📡", name: "Xarunta Xiriirka Telekomunikeeshanka", vocab: ["xiriir", "telefon", "nidaam", "internet", "lacag", "macaamiil", "shaqo"] },
  { emoji: "🏫", name: "Waaxda Waxbarashada", vocab: ["waxbarasho", "maamul", "nidaam", "shaqo", "lacag", "xog", "dowlad"] },
  { emoji: "🏥", name: "Waaxda Caafimaadka", vocab: ["caafimaad", "maamul", "nidaam", "shaqo", "lacag", "xog", "dowlad"] },
  { emoji: "🚒", name: "Waaxda Nabadsugida", vocab: ["nabadsugid", "maamul", "nidaam", "shaqo", "lacag", "xog", "dowlad"] },
  { emoji: "⚖️", name: "Waaxda Cadaaladda", vocab: ["cadaaladda", "sharciga", "dacwad", "nidaam", "xukun", "xog", "maamul"] },
  { emoji: "🌍", name: "Wasaaradda Arrimaha Dibadda", vocab: ["arrimaha dibadda", "safir", "dalka", "nidaam", "xog", "maamul", "dowlad"] },
  { emoji: "🏦", name: "Bangiga Qaranka", vocab: ["bangiga", "lacag", "nidaam", "maamul", "dowlad", "xog", "macaamiil"] },
  { emoji: "🚜", name: "Waaxda Beeraha", vocab: ["beer", "beerista", "nidaam", "maamul", "dowlad", "xog", "lacag"] },
  { emoji: "🛣️", name: "Waaxda Wadooyinka", vocab: ["wadada", "dhisme", "nidaam", "maamul", "dowlad", "lacag", "shaqo"] },

  // ─── DABIICADDA (Nature) ──────────────────────────────────────────────
  { emoji: "🌲", name: "Kaymaha", vocab: ["geedaha", "duur", "xayawaan", "biyo", "hawo", "nadiifin", "dabiici"] },
  { emoji: "🏔️", name: "Buur", vocab: ["buur", "sare", "qabow", "hawada", "duurjoog", "dhagax", "nadiifin"] },
  { emoji: "🏞️", name: "Dooxada", vocab: ["doox", "biyo", "geedaha", "xayawaan", "dabiici", "cagaaran", "nadiifin"] },
  { emoji: "🌊", name: "Bad", vocab: ["bad", "biyo", "mowj", "xayawaan", "kalluun", "joogid", "dabiici"] },
  { emoji: "🏜️", name: "Lamadegaan", vocab: ["lamadegaan", "kuleyl", "ciid", "dhagax", "hawo", "xayawaan", "dabiici"] },
  { emoji: "🌋", name: "Buur Dab-baxa", vocab: ["buur", "dab", "magma", "dabiici", "nidaam", "xog", "cilmi"] },
  { emoji: "💧", name: "Xarafka Biyaha (Waterfall)", vocab: ["biyo", "buur", "xaraf", "dabiici", "muuqaal", "nasasho", "nadiifin"] },
  { emoji: "🌿", name: "Beerta Xayawaanka", vocab: ["xayawaan", "beer", "nasasho", "macaamiil", "nidaam", "ciyaar", "dabiici"] },
  { emoji: "🐘", name: "Beerta Xoolaha", vocab: ["xayawaan", "beer", "nasasho", "macaamiil", "nidaam", "dabiici", "cilmi"] },
  { emoji: "🌅", name: "Badweynta (Open Ocean)", vocab: ["bad", "biyo", "mowj", "kalluun", "dabaash", "xilliga", "dabiici"] },
  { emoji: "🏕️", name: "Kaam", vocab: ["khayme", "duur", "dab", "hawo", "dabiici", "nasasho", "saaxiib"] },
  { emoji: "🌾", name: "Beeraha Galleyda", vocab: ["galley", "beer", "dhul", "biyo", "nidaam", "xilliga", "dabiici"] },
  { emoji: "🍃", name: "Beerta Caabuudka (Botanical Garden)", vocab: ["geedaha", "ubax", "beer", "macaamiil", "nidaam", "dabiici", "muuqaal"] },
  { emoji: "🐬", name: "Goobta Kalluunka Weyn (Aquarium)", vocab: ["kalluun", "biyo", "bad", "macaamiil", "nidaam", "dabiici", "muuqaal"] },
  { emoji: "🌳", name: "Beerta Dalxiiska", vocab: ["geedaha", "beerta", "nasasho", "ciyaar", "macaamiil", "nidaam", "dabiici"] },
  { emoji: "🦁", name: "Beerta Xoolaha (Zoo)", vocab: ["xayawaan", "zoo", "nasasho", "macaamiil", "nidaam", "dabiici", "muuqaal"] },
  { emoji: "🐧", name: "Beerta Shimbiraha", vocab: ["shimbi", "beer", "nasasho", "macaamiil", "nidaam", "dabiici", "muuqaal"] },
  { emoji: "🌺", name: "Beerta Ubaxa", vocab: ["ubax", "beer", "midabyo", "nasasho", "macaamiil", "nidaam", "dabiici"] },
  { emoji: "🏖️", name: "Xeebta Kalluunka", vocab: ["kalluun", "xeeb", "biyo", "nasasho", "macaamiil", "nidaam", "ganacsade"] },
  { emoji: "🏔️", name: "Goobta Dabaashada Buurta", vocab: ["buur", "biyo", "ciyaar", "tababar", "xog", "nidaam", "dabiici"] },
  { emoji: "🌄", name: "Goobta Muuqaalka Buuraha", vocab: ["buur", "muuqaal", "dabiici", "nasasho", "macaamiil", "nidaam", "qurux"] },
  { emoji: "🌙", name: "Goobta Daawashada Xiddigaha", vocab: ["xiddig", "samada", "muuqaal", "dabiici", "nidaam", "qabow", "cilmi"] },
  { emoji: "🌧️", name: "Goobta Roobka", vocab: ["roob", "biyo", "xilliga", "dabiici", "hawo", "nidaam", "nasasho"] },
  { emoji: "❄️", name: "Goobta Barafka", vocab: ["baraf", "qabow", "dabiici", "xilliga", "nidaam", "muuqaal", "nasasho"] },
  { emoji: "🌊", name: "Goobta Dooxada Weyn (Canyon)", vocab: ["doox", "dhagax", "dabiici", "muuqaal", "macaamiil", "nidaam", "buur"] },
  { emoji: "🦅", name: "Goobta Safari", vocab: ["safari", "xayawaan", "dabiici", "muuqaal", "macaamiil", "nidaam", "Afrika"] },
  { emoji: "🌈", name: "Goobta Daawashada Qaansooyinka", vocab: ["qaanso", "muuqaal", "dabiici", "nasasho", "macaamiil", "nidaam", "farxad"] },
  { emoji: "🏝️", name: "Jasiirad", vocab: ["jasiirad", "biyo", "bad", "xeeb", "nasasho", "macaamiil", "nidaam"] },
  { emoji: "🧊", name: "Goobta Glacier", vocab: ["glacier", "baraf", "dabiici", "muuqaal", "macaamiil", "nidaam", "qabow"] },
  { emoji: "🌿", name: "Dooxada Biyo-kululeeyaha", vocab: ["biyo kulul", "buur", "dabiici", "caafimaad", "nidaam", "macaamiil", "muuqaal"] },

  // ─── JOOGITAANKA (Accommodation) ─────────────────────────────────────
  { emoji: "🏨", name: "Hotel", vocab: ["qolka", "nasasho", "adeeg", "marti", "lacag", "nidaam", "macaamiil"] },
  { emoji: "🏡", name: "Villa", vocab: ["villa", "nasasho", "qurux", "marti", "lacag", "nidaam", "macaamiil"] },
  { emoji: "🏩", name: "Hotel Casriga ah (Boutique)", vocab: ["boutique", "nasasho", "qurux", "marti", "lacag", "nidaam", "macaamiil"] },
  { emoji: "⛺", name: "Goobta Khaymaha", vocab: ["khayme", "nasasho", "dabiici", "duur", "marti", "nidaam", "macaamiil"] },
  { emoji: "🏕️", name: "Goobta Camping Resort", vocab: ["camping", "nasasho", "dabiici", "marti", "lacag", "nidaam", "macaamiil"] },
  { emoji: "🏠", name: "Guri Kiradeed", vocab: ["guri", "kirasho", "nasasho", "marti", "lacag", "nidaam", "macaamiil"] },
  { emoji: "🛖", name: "Tukul (Traditional Hut)", vocab: ["tukul", "dhaqan", "nasasho", "dabiici", "marti", "nidaam", "macaamiil"] },
  { emoji: "🚢", name: "Markabka Hotel", vocab: ["markab", "bad", "nasasho", "marti", "lacag", "nidaam", "macaamiil"] },
  { emoji: "🏔️", name: "Lodge (Buur)", vocab: ["buur", "nasasho", "dabiici", "marti", "lacag", "nidaam", "macaamiil"] },
  { emoji: "🏙️", name: "Qolka Magaalada (Apartment)", vocab: ["flat", "magaalo", "nasasho", "marti", "lacag", "nidaam", "macaamiil"] },
  { emoji: "🌴", name: "Resort Xeebta", vocab: ["xeeb", "resort", "nasasho", "marti", "lacag", "nidaam", "macaamiil"] },
  { emoji: "🏚️", name: "Hostel", vocab: ["hostel", "nasasho", "lacag", "marti", "nidaam", "saaxiib", "macaamiil"] },
  { emoji: "🏰", name: "Guri-Qadiimi (Castle Stay)", vocab: ["qadiimi", "taariikh", "nasasho", "marti", "lacag", "nidaam", "macaamiil"] },
  { emoji: "🌿", name: "Eco-Lodge", vocab: ["dabiici", "eco", "nasasho", "marti", "lacag", "nidaam", "macaamiil"] },
  { emoji: "🏖️", name: "Guri Xeebta", vocab: ["xeeb", "nasasho", "biyo", "marti", "lacag", "nidaam", "macaamiil"] },
  { emoji: "🌙", name: "Motel", vocab: ["motel", "nasasho", "baabuur", "marti", "lacag", "nidaam", "macaamiil"] },
  { emoji: "🏠", name: "Guri Qoyska", vocab: ["qoys", "guri", "nasasho", "caafimaad", "macaamiil", "nidaam", "lacag"] },
  { emoji: "🏢", name: "Serviced Apartment", vocab: ["flat", "adeeg", "nasasho", "marti", "lacag", "nidaam", "macaamiil"] },
  { emoji: "🛏️", name: "Bed and Breakfast", vocab: ["subax", "cunto", "nasasho", "marti", "lacag", "nidaam", "macaamiil"] },
  { emoji: "🌄", name: "Farm Stay", vocab: ["beer", "nasasho", "dabiici", "marti", "lacag", "nidaam", "macaamiil"] },

  // ─── FANKA (Arts/Culture) ─────────────────────────────────────────────
  { emoji: "🏛️", name: "Matxaf", vocab: ["taariikh", "sawirka", "aqoon", "daawasho", "fanaan", "macaamiil", "nidaam"] },
  { emoji: "🎨", name: "Galeri Farshaxanka", vocab: ["farshaxan", "sawir", "fanaan", "macaamiil", "nidaam", "daawasho", "qurux"] },
  { emoji: "🎭", name: "Masraxa Dhaqanka", vocab: ["dhaqan", "riwaayad", "fanaan", "macaamiil", "nidaam", "muusig", "daawasho"] },
  { emoji: "🖼️", name: "Goobta Sawirrada", vocab: ["sawir", "fanaan", "macaamiil", "nidaam", "daawasho", "qurux", "farshaxan"] },
  { emoji: "🏺", name: "Matxafka Qadiimiga ah", vocab: ["qadiimi", "taariikh", "aqoon", "macaamiil", "nidaam", "daawasho", "diiwaanka"] },
  { emoji: "📽️", name: "Goobta Fiinooyinka", vocab: ["fiino", "fanaan", "daawasho", "muusig", "macaamiil", "nidaam", "bandhig"] },
  { emoji: "🎶", name: "Goobta Muusigga Dhaqanka", vocab: ["muusig", "dhaqan", "heeso", "fanaan", "macaamiil", "nidaam", "bandhig"] },
  { emoji: "📸", name: "Goobta Sawir-qaadashada", vocab: ["sawir", "fanaan", "qaadid", "macaamiil", "nidaam", "qurux", "daawasho"] },
  { emoji: "🪆", name: "Goobta Farshaxanka Gacanta", vocab: ["gacanta", "farshaxan", "dhaqan", "macaamiil", "nidaam", "qurux", "iibsasho"] },
  { emoji: "🎪", name: "Goobta Circus", vocab: ["circus", "bandhig", "fanaan", "farxad", "macaamiil", "nidaam", "ciyaar"] },
  { emoji: "📰", name: "Xarunta Jaridada", vocab: ["jaridada", "wariye", "xog", "nidaam", "macaamiil", "shaqo", "lacag"] },
  { emoji: "📺", name: "Xarunta TV", vocab: ["TV", "wariye", "xog", "nidaam", "bandhig", "shaqo", "macaamiil"] },
  { emoji: "🎙️", name: "Radiyo", vocab: ["radiyo", "cod", "macaamiil", "nidaam", "bandhig", "xog", "muusig"] },
  { emoji: "📖", name: "Goobta Qoraalada", vocab: ["qoraal", "buug", "aqoon", "fanaan", "macaamiil", "nidaam", "barashada"] },
  { emoji: "🖌️", name: "Goobta Farshaxanka (Studio)", vocab: ["studio", "farshaxan", "fanaan", "sawir", "nidaam", "macaamiil", "qurux"] },
  { emoji: "🎬", name: "Studio Filimka", vocab: ["filin", "fanaan", "nidaam", "sawir", "macaamiil", "studio", "bandhig"] },
  { emoji: "🗿", name: "Goobta Taariikhda Qadiimiga", vocab: ["qadiimi", "taariikh", "aqoon", "macaamiil", "nidaam", "daawasho", "cilmi"] },
  { emoji: "🎭", name: "Goobta Riwaayadda (Theater)", vocab: ["riwaayad", "fanaan", "daawasho", "muusig", "macaamiil", "nidaam", "bandhig"] },
  { emoji: "🎶", name: "Opera House", vocab: ["opera", "muusig", "fanaan", "daawasho", "macaamiil", "nidaam", "codad"] },
  { emoji: "🌍", name: "Xarunta Dhaqanka Soomaalida", vocab: ["dhaqan", "Soomaali", "aqoon", "taariikh", "macaamiil", "nidaam", "bandhig"] },

  // ─── TEKNOOLAJIYADA (Technology) ──────────────────────────────────────
  { emoji: "💻", name: "Xarunta Kompiyuutarka", vocab: ["kombiyuutar", "code", "internet", "nidaam", "shaqo", "tignoolajiya", "xog"] },
  { emoji: "📡", name: "Xarunta Satellite", vocab: ["satellite", "hawada", "xiriir", "nidaam", "tignoolajiya", "xog", "shaqo"] },
  { emoji: "🤖", name: "Shaybaadhka AI", vocab: ["AI", "code", "cilmi", "nidaam", "tignoolajiya", "xog", "shaqo"] },
  { emoji: "🔋", name: "Xarunta Tamarta Qoraxda", vocab: ["koronto", "qorax", "nidaam", "tignoolajiya", "lacag", "xog", "shaqo"] },
  { emoji: "📱", name: "Xarunta Abuurnimada App", vocab: ["app", "telefon", "code", "nidaam", "tignoolajiya", "xog", "shaqo"] },
  { emoji: "🌐", name: "Xarunta Internet", vocab: ["internet", "nidaam", "tignoolajiya", "xog", "shaqo", "xiriir", "code"] },
  { emoji: "🖨️", name: "Xarunta 3D Printing", vocab: ["3D", "daabacaad", "nidaam", "tignoolajiya", "xog", "shaqo", "lacag"] },
  { emoji: "🚗", name: "Xarunta Baabuurta Korsadaha", vocab: ["baabuur", "koronto", "nidaam", "tignoolajiya", "xog", "shaqo", "lacag"] },
  { emoji: "🏭", name: "Warshada Tignoolajiyada", vocab: ["warshad", "tignoolajiya", "nidaam", "xog", "shaqo", "lacag", "alaabtaas"] },
  { emoji: "📊", name: "Xarunta Xogta (Data Center)", vocab: ["xog", "nidaam", "tignoolajiya", "shaqo", "lacag", "internet", "server"] },
  { emoji: "🔭", name: "Xarunta Cilmiga Hawada", vocab: ["hawada", "xiddig", "cilmi", "nidaam", "tignoolajiya", "xog", "shaqo"] },
  { emoji: "🧬", name: "Shaybaadhka Biotechnology", vocab: ["bio", "cilmi", "nidaam", "tignoolajiya", "xog", "shaqo", "baaritaan"] },
  { emoji: "🔬", name: "Shaybaadhka Nanotechnology", vocab: ["nano", "cilmi", "nidaam", "tignoolajiya", "xog", "shaqo", "baaritaan"] },
  { emoji: "⚡", name: "Xarunta Gudbinta Korontada", vocab: ["koronto", "nidaam", "shaqo", "lacag", "alaabtaas", "xog", "macaamiil"] },
  { emoji: "🌊", name: "Xarunta Tamaarta Badda", vocab: ["bad", "tamar", "nidaam", "tignoolajiya", "xog", "shaqo", "lacag"] },

  // ─── BEERUHU (Agriculture/Farm) ───────────────────────────────────────
  { emoji: "🌾", name: "Beerta Galleyda", vocab: ["galley", "beer", "dhul", "biyo", "nidaam", "xilliga", "dabiici"] },
  { emoji: "🥕", name: "Beerta Khudaarta", vocab: ["khudaar", "beer", "dhul", "biyo", "nidaam", "xilliga", "dabiici"] },
  { emoji: "🍎", name: "Beerta Midhaha", vocab: ["miro", "beer", "geedaha", "biyo", "nidaam", "xilliga", "dabiici"] },
  { emoji: "🐄", name: "Xerooyinka Lo'da", vocab: ["lo'", "xoolaha", "beer", "dhul", "nidaam", "xilliga", "dabiici"] },
  { emoji: "🐑", name: "Xerooyinka Adhiga", vocab: ["adhi", "xoolaha", "beer", "dhul", "nidaam", "xilliga", "dabiici"] },
  { emoji: "🐓", name: "Goobta Digaagga", vocab: ["digaag", "xoolaha", "beer", "dhul", "nidaam", "xilliga", "cunto"] },
  { emoji: "🍯", name: "Beerta Shinniida", vocab: ["shinni", "malab", "beer", "ubax", "nidaam", "xilliga", "dabiici"] },
  { emoji: "🌿", name: "Beerta Daawooyinka Dabiiciga ah", vocab: ["dawo", "dabiici", "beer", "geedaha", "nidaam", "xilliga", "cilmi"] },
  { emoji: "🌱", name: "Goobta Abuurista", vocab: ["abuur", "beer", "dhul", "biyo", "nidaam", "xilliga", "dabiici"] },
  { emoji: "🚜", name: "Goobta Beerista", vocab: ["traktarka", "beer", "dhul", "nidaam", "alaabtaas", "lacag", "ganacsade"] },
  { emoji: "🐐", name: "Xerooyinka Riyo", vocab: ["riyo", "xoolaha", "beer", "dhul", "nidaam", "xilliga", "dabiici"] },
  { emoji: "🌻", name: "Beerta Ubaxa (Commercial)", vocab: ["ubax", "beer", "midabyo", "nasasho", "macaamiil", "nidaam", "iibsasho"] },
  { emoji: "🍇", name: "Beerta Canabka", vocab: ["canab", "beer", "geedaha", "biyo", "nidaam", "xilliga", "dabiici"] },
  { emoji: "🌊", name: "Beerta Biyaha (Aquaculture)", vocab: ["biyo", "kalluun", "beer", "nidaam", "xilliga", "dabiici", "ganacsade"] },
  { emoji: "🥜", name: "Beerta Digirta", vocab: ["digir", "beer", "dhul", "biyo", "nidaam", "xilliga", "dabiici"] },

  // ─── XAFLADAHA (Events) ───────────────────────────────────────────────
  { emoji: "💍", name: "Goobta Arooska", vocab: ["aroosad", "qoys", "farxad", "xaflad", "cunto", "muusig", "nidaam"] },
  { emoji: "🎂", name: "Goobta Dhalashada", vocab: ["dhalasho", "farxad", "xaflad", "keeg", "muusig", "saaxiib", "nidaam"] },
  { emoji: "🎓", name: "Goobta Heshiiminta (Graduation)", vocab: ["xafladda", "shahaado", "ardayda", "nidaam", "farxad", "macaamiil", "aqoon"] },
  { emoji: "🕌", name: "Goobta Arooska (Diineed)", vocab: ["aroosad", "diinta", "qoys", "farxad", "xaflad", "cunto", "nidaam"] },
  { emoji: "🎪", name: "Goobta Xafladda Bulshada", vocab: ["xaflad", "bulshada", "farxad", "macaamiil", "nidaam", "muusig", "cunto"] },
  { emoji: "🏆", name: "Goobta Guuleystaha", vocab: ["guul", "tartan", "xaflad", "nidaam", "farxad", "macaamiil", "shahaado"] },
  { emoji: "🎊", name: "Goobta Soo-dhaweynta", vocab: ["soo-dhaweeyn", "farxad", "xaflad", "macaamiil", "nidaam", "muusig", "cunto"] },
  { emoji: "🌸", name: "Goobta Xafladda Ruxaa (Spring Festival)", vocab: ["ubax", "xaflad", "farxad", "macaamiil", "nidaam", "dabiici", "ciyaar"] },
  { emoji: "🪔", name: "Goobta Xafladda Iftiinka", vocab: ["iftiin", "xaflad", "farxad", "macaamiil", "nidaam", "muusig", "cunto"] },
  { emoji: "🎃", name: "Goobta Xafladda Xilliga", vocab: ["xilliga", "xaflad", "farxad", "macaamiil", "nidaam", "ciyaar", "dhaqan"] },

  // ─── GURI/XAAFAD (Home/Neighborhood) ─────────────────────────────────
  { emoji: "🏘️", name: "Xaafad", vocab: ["guri", "deriska", "nidaam", "xilliga", "xariir", "macaamiil", "maamul"] },
  { emoji: "🏠", name: "Guri Qoys", vocab: ["qoys", "guri", "daryeel", "nasasho", "caafimaad", "macaamiil", "nidaam"] },
  { emoji: "🏙️", name: "Magaalo Weyn", vocab: ["magaalo", "baabuur", "shaqo", "nidaam", "macaamiil", "lacag", "xilliga"] },
  { emoji: "🏚️", name: "Goobta Dib-u-Dhisidda", vocab: ["dhisme", "dib-u-dhis", "nidaam", "shaqaale", "lacag", "maamul", "guri"] },
  { emoji: "🛖", name: "Tuulo", vocab: ["tuulo", "qoys", "dhaqan", "nidaam", "macaamiil", "xilliga", "dabiici"] },
  { emoji: "🏗️", name: "Goobta Dhismaha Guriyaha", vocab: ["dhisme", "guri", "nidaam", "shaqaale", "lacag", "maamul", "qalab"] },
  { emoji: "🌳", name: "Beerta Xaafadda", vocab: ["beer", "geedaha", "nasasho", "ciyaar", "xaafad", "nidaam", "macaamiil"] },
  { emoji: "🏊", name: "Berkedda Xaafadda", vocab: ["berked", "biyo", "nasasho", "ciyaar", "xaafad", "nidaam", "macaamiil"] },
  { emoji: "🏋️", name: "Goobta Jimicsiga Xaafadda", vocab: ["jimicsi", "xaafad", "nidaam", "macaamiil", "caafimaad", "lacag", "xilliga"] },
  { emoji: "🚶", name: "Goobta Lugaynta", vocab: ["lugayn", "jidka", "nasasho", "xilliga", "macaamiil", "nidaam", "caafimaad"] },
  { emoji: "🏬", name: "Goobta Ganacsiga Xaafadda", vocab: ["ganacsi", "xaafad", "dukaan", "nidaam", "macaamiil", "lacag", "alaabtaas"] },
  { emoji: "🎭", name: "Xarunta Bulshada Xaafadda", vocab: ["bulshada", "xaafad", "nidaam", "macaamiil", "xiriir", "lacag", "shaqo"] },
  { emoji: "🌆", name: "Bartamaha Magaalada (City Center)", vocab: ["magaalo", "bartame", "nidaam", "baabuur", "shaqo", "macaamiil", "lacag"] },
  { emoji: "🌇", name: "Xaafadda Hore (Suburbs)", vocab: ["xaafad", "nasasho", "guri", "nidaam", "macaamiil", "lacag", "xilliga"] },
  { emoji: "🏡", name: "Guri-Beer (Farmhouse)", vocab: ["guri", "beer", "dabiici", "nasasho", "macaamiil", "nidaam", "lacag"] },
  { emoji: "🌃", name: "Magaalada Habeenka", vocab: ["habeenka", "magaalo", "muusig", "nidaam", "macaamiil", "lacag", "xilliga"] },
  { emoji: "🏠", name: "Guriga Waayeelka (Care Home)", vocab: ["waayeelka", "guri", "daryeel", "nasasho", "caafimaad", "nidaam", "macaamiil"] },
  { emoji: "🛕", name: "Goobta Xusuusta (Memorial)", vocab: ["xusuus", "taariikh", "macaamiil", "nidaam", "daawasho", "dabiici", "muuqaal"] },
  { emoji: "⛲", name: "Beerta Birbiriska (Fountain Park)", vocab: ["biyo", "beer", "nasasho", "macaamiil", "nidaam", "dabiici", "muuqaal"] },
  { emoji: "🌉", name: "Buundada Magaalada", vocab: ["buundo", "magaalo", "nidaam", "baabuur", "jidka", "dabiici", "muuqaal"] },

  // ─── SAFARKA (Travel) ─────────────────────────────────────────────────
  { emoji: "🗼", name: "Taaweerka Magaalada", vocab: ["taaweer", "muuqaal", "macaamiil", "nidaam", "taariikh", "daawasho", "lacag"] },
  { emoji: "🗽", name: "Goobta Taariikh-nooleyaasha", vocab: ["taariikh", "muuqaal", "macaamiil", "nidaam", "daawasho", "dabiici", "qurux"] },
  { emoji: "🏯", name: "Goobta Qasriga Qadiimiga", vocab: ["qadiimi", "taariikh", "macaamiil", "nidaam", "daawasho", "qurux", "muuqaal"] },
  { emoji: "🧳", name: "Xarunta Dalxiiska", vocab: ["dalxiis", "safar", "nidaam", "macaamiil", "lacag", "tiket", "dalka"] },
  { emoji: "🗺️", name: "Xarunta Macluumaadka Safarka", vocab: ["xog", "dalxiis", "nidaam", "macaamiil", "safar", "tiket", "dalka"] },
  { emoji: "📸", name: "Goobta Sawir-qaadashada Dalxiiska", vocab: ["sawir", "macaamiil", "nidaam", "daawasho", "dalxiis", "qurux", "muuqaal"] },
  { emoji: "🌍", name: "Xarunta Safarka Adduunka", vocab: ["adduunka", "safar", "dalka", "nidaam", "macaamiil", "tiket", "lacag"] },
  { emoji: "🎒", name: "Goobta Backpacker", vocab: ["backpacker", "safar", "dalka", "nidaam", "macaamiil", "lacag", "saaxiib"] },
  { emoji: "🛥️", name: "Goobta Safarka Badda", vocab: ["bad", "safar", "dalka", "nidaam", "macaamiil", "tiket", "lacag"] },
  { emoji: "🚂", name: "Goobta Tareenka Dalxiiska", vocab: ["tareen", "dalxiis", "safar", "nidaam", "macaamiil", "tiket", "dalka"] },
  { emoji: "🌄", name: "Goobta Muuqaalka Dabiiciga", vocab: ["muuqaal", "dabiici", "qurux", "nasasho", "macaamiil", "nidaam", "dalxiis"] },
  { emoji: "🌺", name: "Goobta Rafaxanka Xilliyadaha (Seasonal Resort)", vocab: ["xilliga", "resort", "nasasho", "macaamiil", "nidaam", "lacag", "dalxiis"] },
  { emoji: "🎡", name: "Xarunta Madadaalada Dalxiiska", vocab: ["madadaalo", "dalxiis", "macaamiil", "nidaam", "lacag", "farxad", "ciyaar"] },
  { emoji: "🏟️", name: "Garoonka Weyn (Stadium)", vocab: ["garoon", "ciyaar", "tartanka", "macaamiil", "nidaam", "lacag", "xilliga"] },
  { emoji: "🗿", name: "Goobta Aasaasiga Qadiimiga", vocab: ["qadiimi", "taariikh", "aqoon", "macaamiil", "nidaam", "daawasho", "cilmi"] },

  // ─── BADDA/DOOXA (Sea/Water) ───────────────────────────────────────────
  { emoji: "🏖️", name: "Xeebta Nasashada", vocab: ["xeeb", "biyo", "nasasho", "macaamiil", "nidaam", "ciid", "mowj"] },
  { emoji: "🤿", name: "Goobta Dhex-galida Badda", vocab: ["diving", "biyo", "bad", "xayawaan", "nidaam", "macaamiil", "ciyaar"] },
  { emoji: "⛵", name: "Goobta Doon-xidista", vocab: ["doon", "bad", "safar", "nidaam", "macaamiil", "lacag", "xilliga"] },
  { emoji: "🐟", name: "Goobta Kalluunsashada", vocab: ["kalluun", "bad", "biyo", "nidaam", "macaamiil", "ciyaar", "dabiici"] },
  { emoji: "🏄", name: "Goobta Mowj-xidhka", vocab: ["mowj", "bad", "ciyaar", "xawli", "macaamiil", "nidaam", "nasasho"] },
  { emoji: "🚤", name: "Goobta Speedboatka", vocab: ["speedboat", "bad", "xawli", "nidaam", "macaamiil", "ciyaar", "lacag"] },
  { emoji: "🌊", name: "Goobta Kalluunsashada Weyn", vocab: ["kalluun", "weyn", "bad", "nidaam", "macaamiil", "ganacsade", "dabiici"] },
  { emoji: "🐬", name: "Goobta Daawashada Doofaarka", vocab: ["doofaar", "biyo", "bad", "macaamiil", "nidaam", "daawasho", "dabiici"] },
  { emoji: "⛴️", name: "Goobta Ferry", vocab: ["ferry", "bad", "safar", "tiket", "rakaab", "nidaam", "deked"] },
  { emoji: "🏝️", name: "Jasiiraadda Dalxiiska", vocab: ["jasiirad", "dalxiis", "bad", "nasasho", "macaamiil", "nidaam", "lacag"] },
  { emoji: "🪸", name: "Goobta Birbirska (Coral Reef)", vocab: ["coral", "biyo", "bad", "xayawaan", "nidaam", "daawasho", "dabiici"] },
  { emoji: "🌅", name: "Goobta Qoraxda Baxda Badda", vocab: ["qorax", "bad", "muuqaal", "macaamiil", "nidaam", "nasasho", "dabiici"] },
  { emoji: "🛶", name: "Goobta Waraabaha (Canoe)", vocab: ["waraabbe", "biyo", "ciyaar", "nidaam", "macaamiil", "dabiici", "nasasho"] },
  { emoji: "⚓", name: "Dekedda Dalxiiska", vocab: ["deked", "dalxiis", "bad", "macaamiil", "nidaam", "lacag", "safar"] },
  { emoji: "🌊", name: "Webiga (River)", vocab: ["webi", "biyo", "dabiici", "nasasho", "macaamiil", "nidaam", "kalluun"] },
  { emoji: "🏊", name: "Berkedda Badda", vocab: ["berked", "bad", "biyo", "nasasho", "macaamiil", "nidaam", "ciyaar"] },
  { emoji: "🦀", name: "Suuqa Kalluunka (Port Market)", vocab: ["kalluun", "suuq", "bad", "ganacsade", "nidaam", "macaamiil", "qiime"] },
  { emoji: "🌊", name: "Goobta Dhumucda Badda (Deep Sea)", vocab: ["bad", "biyo", "cilmi", "xayawaan", "nidaam", "dabiici", "baaritaan"] },
  { emoji: "🏖️", name: "Xeebta Ciyaaraha", vocab: ["ciyaar", "xeeb", "biyo", "farxad", "macaamiil", "nidaam", "nasasho"] },
  { emoji: "🚢", name: "Markab-Weyn (Cruise Ship)", vocab: ["markab", "bad", "nasasho", "macaamiil", "lacag", "nidaam", "safar"] },

  // ─── CIIDANKA (Military/Security) ─────────────────────────────────────
  { emoji: "🏰", name: "Saldhigga Ciidanka", vocab: ["ciidan", "nidaam", "shaqo", "hub", "shaqaale", "maamul", "xog"] },
  { emoji: "🚔", name: "Saddexaadka Booliska (Police Checkpoint)", vocab: ["booliska", "sharciga", "nidaam", "hub", "xog", "maamul", "jidka"] },
  { emoji: "🎖️", name: "Xarunta Dhaxalka Ciidanka", vocab: ["ciidan", "sharaf", "nidaam", "hub", "shaqaale", "maamul", "taariikh"] },
  { emoji: "🚁", name: "Goobta Hallaybaariga Ciidanka", vocab: ["ciidan", "hallaybaarig", "nidaam", "hub", "shaqaale", "degdeg", "xog"] },
  { emoji: "🚒", name: "Saldhigga Xarunta Gargaarka", vocab: ["gargaar", "degdeg", "nidaam", "hub", "shaqaale", "maamul", "baabuur"] },
  { emoji: "🔭", name: "Goobta Xog-ururintah (Intelligence)", vocab: ["xog", "sir", "nidaam", "maamul", "hub", "shaqaale", "cilmi"] },
  { emoji: "🛡️", name: "Xarunta Nabadsugida", vocab: ["nabadsugid", "nidaam", "hub", "shaqaale", "maamul", "sharciga", "xog"] },
  { emoji: "⚔️", name: "Goobta Tababarka Ciidanka", vocab: ["tababar", "ciidan", "nidaam", "hub", "shaqaale", "maamul", "xog"] },
  { emoji: "🏥", name: "Isbitaalka Ciidanka", vocab: ["ciidan", "bukaan", "daaweyn", "nidaam", "hub", "shaqaale", "caafimaad"] },
  { emoji: "📡", name: "Xarunta Xiriirka Ciidanka", vocab: ["xiriir", "ciidan", "nidaam", "hub", "shaqaale", "maamul", "xog"] },
  { emoji: "🚧", name: "Goobta Xakameynta Xadka", vocab: ["xad", "dalka", "nidaam", "hub", "shaqaale", "maamul", "booliska"] },
  { emoji: "🏗️", name: "Goobta Dhismaha Ciidanka", vocab: ["dhisme", "ciidan", "nidaam", "hub", "shaqaale", "maamul", "qalab"] },
  { emoji: "🌐", name: "Xarunta Cyber-Security", vocab: ["cyber", "nidaam", "hub", "shaqaale", "maamul", "internet", "xog"] },
  { emoji: "🐕", name: "Goobta Eyga Booliska", vocab: ["ey", "booliska", "nidaam", "hub", "shaqaale", "maamul", "xog"] },
  { emoji: "🚨", name: "Goobta Gargaarka Degdegga", vocab: ["degdeg", "gargaar", "nidaam", "hub", "shaqaale", "maamul", "baabuur"] },

  // ─── DHAQAALAHA (Finance) ─────────────────────────────────────────────
  { emoji: "🏦", name: "Bangiga Dhexe", vocab: ["lacag", "bangiga", "nidaam", "maamul", "dowlad", "xog", "macaamiil"] },
  { emoji: "📈", name: "Xarunta Suuqa Hantida", vocab: ["hanti", "suuq", "lacag", "nidaam", "maamul", "ganacsi", "xog"] },
  { emoji: "💱", name: "Goobta Beddelka Lacagta", vocab: ["lacag", "bedel", "nidaam", "macaamiil", "ganacsi", "xog", "shirkad"] },
  { emoji: "🏧", name: "ATM (Mishiinka Lacagta)", vocab: ["ATM", "lacag", "nidaam", "macaamiil", "kaarka", "xog", "shirkad"] },
  { emoji: "💳", name: "Xarunta Kaarka Lacagta", vocab: ["kaar", "lacag", "nidaam", "macaamiil", "shirkad", "xog", "ganacsi"] },
  { emoji: "📊", name: "Xarunta Falanqaynta Dhaqaalaha", vocab: ["dhaqaale", "falanqayn", "lacag", "nidaam", "xog", "maamul", "shirkad"] },
  { emoji: "💰", name: "Goobta Deeqaha (Loan Office)", vocab: ["deeq", "lacag", "nidaam", "macaamiil", "shirkad", "xog", "heshiis"] },
  { emoji: "📉", name: "Xarunta Maalgashiga", vocab: ["maalgashi", "lacag", "nidaam", "macaamiil", "shirkad", "xog", "hanti"] },
  { emoji: "🧾", name: "Xarunta Cashuurta", vocab: ["cashuur", "lacag", "nidaam", "maamul", "dowlad", "xog", "macaamiil"] },
  { emoji: "🤝", name: "Goobta Heshiisyada Ganacsi", vocab: ["heshiis", "ganacsi", "lacag", "nidaam", "macaamiil", "shirkad", "xog"] },
  { emoji: "💼", name: "Xarunta Caymiska", vocab: ["caymis", "lacag", "nidaam", "macaamiil", "shirkad", "xog", "heshiis"] },
  { emoji: "🪙", name: "Xarunta Cryptocurrency", vocab: ["crypto", "lacag", "nidaam", "internet", "xog", "shirkad", "ganacsi"] },
  { emoji: "🏗️", name: "Xarunta Maalgashiga Guryaha", vocab: ["guri", "maalgashi", "lacag", "nidaam", "shirkad", "xog", "hanti"] },
  { emoji: "🛒", name: "Xarunta Furitaanka Ganacsiga", vocab: ["ganacsi", "lacag", "nidaam", "macaamiil", "shirkad", "xog", "heshiis"] },
  { emoji: "💵", name: "Goobta Hawaaladaha", vocab: ["hawaala", "lacag", "nidaam", "macaamiil", "xog", "shirkad", "bedel"] },

  // ─── WARSHADAHA (Industry) ────────────────────────────────────────────
  { emoji: "🏭", name: "Warshada Cabitaanka", vocab: ["cabitaan", "warshad", "wax soo saar", "nidaam", "lacag", "alaabtaas", "shaqaale"] },
  { emoji: "🧴", name: "Warshada Alaabta Nadaafada", vocab: ["nadaafad", "warshad", "wax soo saar", "nidaam", "lacag", "alaabtaas", "shaqaale"] },
  { emoji: "👗", name: "Warshada Dharka", vocab: ["dhar", "warshad", "wax soo saar", "nidaam", "lacag", "alaabtaas", "shaqaale"] },
  { emoji: "🛠️", name: "Warshada Qalabka", vocab: ["qalab", "warshad", "wax soo saar", "nidaam", "lacag", "alaabtaas", "shaqaale"] },
  { emoji: "🔩", name: "Warshada Bir-gashka", vocab: ["bir", "warshad", "wax soo saar", "nidaam", "lacag", "alaabtaas", "shaqaale"] },
  { emoji: "🏗️", name: "Warshada Xarafta", vocab: ["xaraf", "warshad", "wax soo saar", "nidaam", "lacag", "alaabtaas", "shaqaale"] },
  { emoji: "🚗", name: "Warshada Baabuurta", vocab: ["baabuur", "warshad", "wax soo saar", "nidaam", "lacag", "alaabtaas", "shaqaale"] },
  { emoji: "⚡", name: "Xarunta Koronto-Soo-saarka", vocab: ["koronto", "nidaam", "shaqo", "lacag", "alaabtaas", "xog", "macaamiil"] },
  { emoji: "🛢️", name: "Warshada Shidaalka", vocab: ["shidaal", "warshad", "wax soo saar", "nidaam", "lacag", "alaabtaas", "shaqaale"] },
  { emoji: "🌿", name: "Warshada Dawooyinka", vocab: ["dawo", "warshad", "wax soo saar", "nidaam", "lacag", "alaabtaas", "caafimaad"] },
  { emoji: "🧱", name: "Warshada Dhismaha", vocab: ["dhisme", "warshad", "wax soo saar", "nidaam", "lacag", "alaabtaas", "shaqaale"] },
  { emoji: "🍞", name: "Warshada Cuntada", vocab: ["cunto", "warshad", "wax soo saar", "nidaam", "lacag", "alaabtaas", "shaqaale"] },
  { emoji: "📦", name: "Xarunta Raridda", vocab: ["xamuul", "warshad", "nidaam", "lacag", "alaabtaas", "shaqaale", "gaadiid"] },
  { emoji: "🌊", name: "Warshada Nadiifinta Biyaha", vocab: ["biyo", "nadiifin", "warshad", "nidaam", "lacag", "alaabtaas", "shaqaale"] },
  { emoji: "🌱", name: "Warshada Compostka", vocab: ["qashin", "dabiici", "warshad", "nidaam", "lacag", "alaabtaas", "nadiifin"] },

  // ─── DUKAAMMADA GAARKA AH (Specialty Shops) ───────────────────────────
  { emoji: "🧶", name: "Dukaanka Dhar-Gelidda", vocab: ["dhar", "xidid", "gacanta", "qiime", "iibsasho", "macaamiil", "nidaam"] },
  { emoji: "🕶️", name: "Dukaanka Muraayadaha", vocab: ["muraayad", "indhaha", "qiime", "iibsasho", "macaamiil", "nidaam", "casri"] },
  { emoji: "🪒", name: "Dukaanka Xallinta Timaha (Barber)", vocab: ["timaha", "xallin", "dhakhtar", "macaamiil", "qiime", "nidaam", "qurux"] },
  { emoji: "💇", name: "Salon Dumarka", vocab: ["timaha", "qurux", "macaamiil", "qiime", "nidaam", "xallin", "dhar"] },
  { emoji: "🎀", name: "Dukaanka Qaliinka", vocab: ["qaliin", "warqad", "qiime", "iibsasho", "macaamiil", "nidaam", "shaqo"] },
  { emoji: "🧸", name: "Dukaanka Ciyaaraha Carruurta", vocab: ["ciyaar", "carruurta", "qiime", "iibsasho", "macaamiil", "nidaam", "farxad"] },
  { emoji: "🪞", name: "Dukaanka Alaabta Guriga", vocab: ["alaab", "guri", "qiime", "iibsasho", "macaamiil", "nidaam", "casri"] },
  { emoji: "🌿", name: "Dukaanka Dhirta Guriga", vocab: ["dhir", "ubax", "guri", "qiime", "iibsasho", "macaamiil", "nidaam"] },
  { emoji: "📷", name: "Dukaanka Sawir-qaadashada", vocab: ["sawir", "qalab", "qiime", "iibsasho", "macaamiil", "nidaam", "fanaan"] },
  { emoji: "🎵", name: "Dukaanka CDyada", vocab: ["muusig", "CD", "qiime", "iibsasho", "macaamiil", "nidaam", "fanaan"] },
  { emoji: "🧩", name: "Dukaanka Ciyaaraha Maskaxda", vocab: ["ciyaar", "maskax", "qiime", "iibsasho", "macaamiil", "nidaam", "farxad"] },
  { emoji: "🪙", name: "Dukaanka Lacagta Qadiimiga", vocab: ["lacag", "qadiimi", "qiime", "iibsasho", "macaamiil", "nidaam", "taariikh"] },
  { emoji: "🎭", name: "Dukaanka Dharka Masraxa", vocab: ["dhar", "masrax", "qiime", "iibsasho", "macaamiil", "nidaam", "fanaan"] },
  { emoji: "🐾", name: "Dukaanka Xoolaha Guriga", vocab: ["xoolaha", "guri", "qiime", "iibsasho", "macaamiil", "nidaam", "daryeel"] },
  { emoji: "🧲", name: "Dukaanka Qalab-Dib-u-Celinta", vocab: ["dib-u-cel", "qalab", "qiime", "iibsasho", "macaamiil", "nidaam", "shaqo"] },

  // ─── BANNAANKA (Outdoor) ──────────────────────────────────────────────
  { emoji: "⛺", name: "Goobta Khaymaha", vocab: ["khayme", "duur", "dabiici", "dab", "nasasho", "saaxiib", "hawo"] },
  { emoji: "🏕️", name: "Goobta Camping Dalxiiska", vocab: ["camping", "dalxiis", "dabiici", "hawo", "macaamiil", "nidaam", "nasasho"] },
  { emoji: "🌲", name: "Goobta Socod-ee-Kaynta", vocab: ["kayn", "geedaha", "socod", "hawo", "macaamiil", "nidaam", "dabiici"] },
  { emoji: "🚵", name: "Goobta Baaskiilka Buurta", vocab: ["baaskiil", "buur", "ciyaar", "xog", "nidaam", "tababar", "dabiici"] },
  { emoji: "🏹", name: "Goobta Kalluunsashada", vocab: ["kalluun", "ciyaar", "dabiici", "biyo", "macaamiil", "nidaam", "nasasho"] },
  { emoji: "🧗", name: "Goobta Dhagax-Fuulka", vocab: ["dhagax", "xoog", "fuul", "ciyaar", "dabiici", "nidaam", "tababar"] },
  { emoji: "🏞️", name: "Xarunta Parkada Qaranka", vocab: ["park", "dabiici", "macaamiil", "nidaam", "nasasho", "lacag", "hawo"] },
  { emoji: "🌄", name: "Goobta Daawashada Sare", vocab: ["sare", "muuqaal", "dabiici", "nasasho", "macaamiil", "nidaam", "qurux"] },
  { emoji: "🏖️", name: "Goobta Qaybta Xeebta", vocab: ["xeeb", "biyo", "ciyaar", "nasasho", "macaamiil", "nidaam", "dabiici"] },
  { emoji: "🌺", name: "Beerta Dabiiciga", vocab: ["dabiici", "ubax", "geedaha", "nasasho", "macaamiil", "nidaam", "qurux"] },
  { emoji: "🎣", name: "Goobta Kalluunsashada (Pier)", vocab: ["pier", "kalluun", "biyo", "ciyaar", "macaamiil", "nidaam", "nasasho"] },
  { emoji: "🚣", name: "Goobta Waraabaha Webiga", vocab: ["waraabbe", "webi", "biyo", "ciyaar", "macaamiil", "nidaam", "dabiici"] },
  { emoji: "🌿", name: "Goobta Xilliga Geedaha", vocab: ["geedaha", "dabiici", "xilliga", "nasasho", "macaamiil", "nidaam", "muuqaal"] },
  { emoji: "🌱", name: "Beerta Culus-ee-Dabiiciga", vocab: ["dabiici", "beer", "geedaha", "nasasho", "macaamiil", "nidaam", "qurux"] },
  { emoji: "🦋", name: "Goobta Balanbaalisyada", vocab: ["balanbaalis", "dabiici", "ubax", "macaamiil", "nidaam", "qurux", "muuqaal"] },
  { emoji: "⛷️", name: "Goobta Dhoobada (Mud Trekking)", vocab: ["dhoobo", "buur", "ciyaar", "dabiici", "nidaam", "macaamiil", "xog"] },
  { emoji: "🌊", name: "Goobta Mowjaha (Surf Beach)", vocab: ["mowj", "xeeb", "ciyaar", "dabiici", "macaamiil", "nidaam", "xawli"] },
  { emoji: "🏔️", name: "Goobta Fuulidda Buurta", vocab: ["buur", "fuul", "ciyaar", "dabiici", "macaamiil", "nidaam", "xog"] },
  { emoji: "🌙", name: "Goobta Khaymaha Habeenka", vocab: ["habeenka", "khayme", "dabiici", "nasasho", "macaamiil", "nidaam", "xiddig"] },
  { emoji: "🌅", name: "Goobta Bilawga Maalinta (Dawn)", vocab: ["subax", "qorax", "dabiici", "nasasho", "macaamiil", "nidaam", "muuqaal"] },

  // ─── GOOBAHA BULSHADA (Community) ─────────────────────────────────────
  { emoji: "🏥", name: "Xarunta Gargaarka Bulshada", vocab: ["gargaar", "bulshada", "nidaam", "macaamiil", "shaqo", "lacag", "maamul"] },
  { emoji: "🍽️", name: "Goobta Cuntada Saboolka (Food Bank)", vocab: ["cunto", "gargaar", "saboolka", "nidaam", "macaamiil", "shaqo", "maamul"] },
  { emoji: "📚", name: "Xarunta Waxbarashada Dadweynaha", vocab: ["waxbarasho", "bulshada", "nidaam", "macaamiil", "shaqo", "lacag", "aqoon"] },
  { emoji: "🏛️", name: "Gole-Hoosaadka Bulshada", vocab: ["gole", "bulshada", "nidaam", "maamul", "shaqo", "lacag", "xog"] },
  { emoji: "🌍", name: "Xarunta Deegaanka", vocab: ["deegaan", "bulshada", "nidaam", "macaamiil", "shaqo", "lacag", "maamul"] },
  { emoji: "🤝", name: "Goobta Iskaashiga", vocab: ["iskaashi", "bulshada", "nidaam", "macaamiil", "shaqo", "lacag", "maamul"] },
  { emoji: "🏗️", name: "Xarunta Dhismaha Bulshada", vocab: ["dhisme", "bulshada", "nidaam", "macaamiil", "shaqo", "lacag", "maamul"] },
  { emoji: "🎭", name: "Goobta Fanka Bulshada", vocab: ["farshaxan", "bulshada", "nidaam", "macaamiil", "shaqo", "lacag", "bandhig"] },
  { emoji: "🏋️", name: "Xarunta Jimicsiga Bulshada", vocab: ["jimicsi", "bulshada", "nidaam", "macaamiil", "caafimaad", "lacag", "shaqo"] },
  { emoji: "🌱", name: "Beerta Bulshada", vocab: ["beer", "bulshada", "dabiici", "nidaam", "macaamiil", "shaqo", "lacag"] },
  { emoji: "📺", name: "Xarunta TV-ga Bulshada", vocab: ["TV", "bulshada", "nidaam", "macaamiil", "shaqo", "lacag", "bandhig"] },
  { emoji: "🎓", name: "Goobta Shahaadada Bulshada", vocab: ["shahaado", "bulshada", "nidaam", "macaamiil", "shaqo", "lacag", "aqoon"] },
  { emoji: "💊", name: "Xarunta Caafimaadka Bulshada", vocab: ["caafimaad", "bulshada", "nidaam", "macaamiil", "shaqo", "lacag", "dawo"] },
  { emoji: "🧒", name: "Goobta Daryeelka Carruurta", vocab: ["carruurta", "daryeel", "nidaam", "macaamiil", "shaqo", "lacag", "caafimaad"] },
  { emoji: "🌿", name: "Goobta Dabiiciga Bulshada", vocab: ["dabiici", "bulshada", "nidaam", "macaamiil", "shaqo", "lacag", "nadiifin"] },
];

export function getRandomLocation(excludeName?: string): Location {
  const available = excludeName
    ? LOCATIONS.filter((l) => l.name !== excludeName)
    : LOCATIONS;
  return available[Math.floor(Math.random() * available.length)];
}
